# Field names taken from https://content.u-blox.com/sites/default/files/documents/u-blox-F9-HPG-1.32_InterfaceDescription_UBX-22008968.pdf

std_msgs/Header header

uint32 itow
float64 lon
float64 lat
float64 height
float64 hmsl
float32 h_acc
float32 v_acc
float32 vel_n
float32 vel_e
float32 vel_d
float32 speed
float32 g_speed
float32 heading
float32 s_acc
bool pos_cov_valid
bool vel_cov_valid
float32 pos_cov_nn
float32 pos_cov_ne
float32 pos_cov_nd
float32 pos_cov_ee
float32 pos_cov_ed
float32 pos_cov_dd
float32 vel_cov_nn
float32 vel_cov_ne
float32 vel_cov_nd
float32 vel_cov_ee
float32 vel_cov_ed
float32 vel_cov_dd
